[package]
name = "featured"
version = "0.1.0"
authors = ["The ChromiumOS Authors"]
edition = "2021"

[dependencies]
once_cell = "1"
thiserror = "1.0.30"

[build-dependencies]
bindgen = "0.64"

[dev-dependencies]
log = "0.4"
